- name: "reboot : check if reboot required"
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: "reboot : saving state"
  set_fact:
    need_reboot: "{{ reboot_required.stat.exists is defined and reboot_required.stat.exists }}"

- name: "reboot : confirm"
  pause:
    prompt: "About to reboot {{ item }}. Press enter to continue or ctrl-c to abort"
  when: hostvars[item]['need_reboot']
  with_items: "{{ play_hosts }}"

- name: "reboot : server"
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true
  when: item == inventory_hostname and hostvars[item]['need_reboot']
  with_items: "{{ play_hosts }}"

- name: "reboot : wait for server to come back online"
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=10 timeout=300
  when: hostvars[item]['need_reboot']
  with_items: "{{ play_hosts }}"
