- name: "users : fix sudoers secure path"
  lineinfile:
    destfile: /etc/sudoers
    regexp: "^Defaults\\s+secure_path\\s*="
    line: "Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
    validate: 'visudo -cf %s'
  become: true

- name: "users : add colours to root prompt"
  lineinfile:
    destfile: /root/.bashrc
    regexp: "^PS1="
    line: "PS1='\\[\\e[31;1m\\]\\u\\[\\e[m\\]@\\[\\e[32m\\]\\h:\\[\\e[33;1m\\]\\w\\[\\e[m\\]\\$ '"
  become: true

- name: "users : add colours to user prompt"
  lineinfile:
    destfile: ~/.bashrc
    regexp: "^PS1="
    line: "PS1='\\[\\e[36m\\]\\u\\[\\e[m\\]@\\[\\e[32m\\]\\h:\\[\\e[33;1m\\]\\w\\[\\e[m\\]\\$ '"
